import * as fs from "node:fs";
import * as path from "node:path";

const GENERATED_DIR = path.resolve(__dirname, "../generated/client");
const GENERATED_BROWSER = path.join(GENERATED_DIR, "browser.ts");
const OUTPUT = path.resolve(__dirname, "../index.ts");

// Post-process: fix .js import specifiers to .ts in generated files
// Prisma v7 generates .ts files with .js import paths (ESM convention),
// but Turbopack (Next.js 16+) doesn't resolve .js → .ts.
function fixJsImportExtensions(dir: string) {
	const entries = fs.readdirSync(dir, { withFileTypes: true });
	for (const entry of entries) {
		const fullPath = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			fixJsImportExtensions(fullPath);
		} else if (entry.name.endsWith(".ts")) {
			let content = fs.readFileSync(fullPath, "utf-8");
			const updated = content
				.replace(/(from\s+['"])(\.[^'"]+)\.js(['"])/g, "$1$2.ts$3")
				.replace(/(import\s+['"])(\.[^'"]+)\.js(['"])/g, "$1$2.ts$3");
			if (updated !== content) {
				fs.writeFileSync(fullPath, updated, "utf-8");
			}
		}
	}
}

fixJsImportExtensions(GENERATED_DIR);
console.log("Fixed .js import extensions in generated client files.");

function collectExports(
	filePath: string,
	typeExports: Set<string>,
	valueExports: Set<string>,
) {
	const content = fs.readFileSync(filePath, "utf-8");
	let depth = 0;

	for (const line of content.split("\n")) {
		const openBraces = (line.match(/\{/g) || []).length;
		const closeBraces = (line.match(/\}/g) || []).length;

		const isTopLevel = depth === 0;
		depth += openBraces - closeBraces;

		if (!isTopLevel) continue;

		// export * from './foo.js' — follow the re-export
		const starReExport = line.match(/^export \* from ['"](.+)['"]/);
		if (starReExport?.[1]) {
			const target = starReExport[1].replace(/\.js$/, ".ts");
			const targetPath = path.resolve(path.dirname(filePath), target);
			if (fs.existsSync(targetPath)) {
				collectExports(targetPath, typeExports, valueExports);
			}
			continue;
		}

		// export type * from './foo.js' — follow type-only re-export
		const typeStarReExport = line.match(/^export type \* from ['"](.+)['"]/);
		if (typeStarReExport?.[1]) {
			const target = typeStarReExport[1].replace(/\.js$/, ".ts");
			const targetPath = path.resolve(path.dirname(filePath), target);
			if (fs.existsSync(targetPath)) {
				collectExports(targetPath, typeExports, valueExports);
			}
			continue;
		}

		// export type Foo = ...
		const typeMatch = line.match(/^export type ([\w$]+)\s*[=<]/);
		if (typeMatch?.[1]) {
			typeExports.add(typeMatch[1]);
			continue;
		}

		// export const Foo: ... or export const Foo = ...
		const constMatch = line.match(/^export const ([\w$]+)[:<= ]/);
		if (constMatch?.[1]) {
			valueExports.add(constMatch[1]);
			continue;
		}

		// export class Foo
		const classMatch = line.match(/^export class ([\w$]+)/);
		if (classMatch?.[1]) {
			valueExports.add(classMatch[1]);
			continue;
		}

		// export namespace Foo
		const nsMatch = line.match(/^export namespace ([\w$]+)/);
		if (nsMatch?.[1]) {
			valueExports.add(nsMatch[1]);
		}

		// export { Foo } or export { Foo } from '...'
		const namedExportMatch = line.match(/^export \{ ([\w$, ]+) \}/);
		if (namedExportMatch?.[1]) {
			for (const name of namedExportMatch[1].split(",").map((s) => s.trim())) {
				if (name) valueExports.add(name);
			}
		}

		// export * as Foo from '...'
		const starAsMatch = line.match(/^export \* as ([\w$]+) from/);
		if (starAsMatch?.[1]) {
			valueExports.add(starAsMatch[1]);
		}
	}
}

const typeExports = new Set<string>();
const valueExports = new Set<string>();

collectExports(GENERATED_BROWSER, typeExports, valueExports);

// Names that exist as both type and value should only appear in value exports
const pureTypes = [...typeExports].filter((t) => !valueExports.has(t));
const values = [...valueExports];

// Use browser.ts as the source to avoid pulling in Node.js-only runtime deps.
// For the prisma client instance, import from 'database/client' instead.
const lines = [
	"// This file is auto-generated by scripts/generate-exports.ts",
	"// Do not edit manually. Run `pnpm db:generate` to regenerate.",
	"// NOTE: This exports from browser.ts (no Node.js runtime deps).",
	"// For the prisma instance, import from 'database/client' instead.",
	"",
];

if (values.length > 0) {
	lines.push(
		`export {\n  ${values.join(",\n  ")},\n} from './generated/client/browser'`,
	);
}

if (pureTypes.length > 0) {
	lines.push(
		`export type {\n  ${pureTypes.join(",\n  ")},\n} from './generated/client/browser'`,
	);
}

lines.push("");

fs.writeFileSync(OUTPUT, lines.join("\n"), "utf-8");
console.log(
	`Generated index.ts with ${values.length} value exports and ${pureTypes.length} type exports.`,
);
