packages:
  - apps/*
  - packages/*

catalogs:
  default:
    '@prisma/adapter-pg': 7.5.0
    '@prisma/client': 7.5.0
    '@types/node': 20.19.37
    '@types/react': 19.2.14
    '@types/react-dom': 19.2.3
    next: 16.1.7
    pg: 8.16.0
    prisma: 7.5.0
    react: 19.2.4
    react-dom: 19.2.4
    typescript: 5.9.3
